# Site settings
port: 80
baseurl: ""
url: "http://localhost" # the base hostname & protocol for your site
title: "Coding thoughts"
description: "We codelinker, code and solve the real world problems."


# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Sass settings
sass:
    style: :compressed