# Site settings
port: 80
baseurl: ""
url: "http://blog.codelink.in" # the base hostname & protocol for your site
title: "Codelink Blog"
description: "Insights from Codelinkers into our products, technology, and the Codelink culture."

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Sass settings
sass:
    style: :compressed
